import Head from "next/head";
import Image from "next/image";
import s from "../styles/Home.module.scss";

import { useState, useEffect } from "react";
import { db } from "../firebase";

export default function Home() {
  const [mentor, setMentor] = useState("");
  const [mentorp, setMentorp] = useState("");

  const [departmentUUID, setdepartmentUUID] = useState("");
  const [departmentPassword, setdepartmentPassword] = useState("");
  const [collegeUUID, setcollegeUUID] = useState("");

  const DepartmentLogin = () => {
    db.collection(`colleges/${collegeUUID}/Departments`)
      .doc(departmentUUID)
      .get()
      .then((doc) => {
        let details = doc.data();
        if (details.password == departmentPassword) {
          localStorage.setItem("departmentUUID", departmentUUID);
          localStorage.setItem("collegeUUID", collegeUUID);
        }
      });
  };

  return (
    <div className={s.container}>
      <Head>
        <title>projects.io Administration</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* 
      <div className={s.Login}>
        <h1>Mentor Login</h1>
        <div className={s.InputBox}>
          <input
            placeholder="MentorName"
            onChange={(e) => setMentor(e.target.value)}
          ></input>
        </div>
        <div className={s.InputBox}>
          <input
            type="password"
            placeholder="MentorPassword"
            onChange={(e) => setMentorp(e.target.value)}
          ></input>
        </div>
        <button className={s.LogBtn}>Login</button>
      </div> */}
      <div className={s.Login}>
        <h1>Department Login</h1>
        <div className={s.InputBox}>
          <input
            placeholder="departmentUUID"
            onChange={(e) => setdepartmentUUID(e.target.value)}
          ></input>
        </div>
        <div className={s.InputBox}>
          <input
            type="password"
            placeholder="departmentPassword"
            onChange={(e) => setdepartmentPassword(e.target.value)}
          ></input>
        </div>
        <div className={s.InputBox}>
          <input
            placeholder="collegeUUID"
            onChange={(e) => setcollegeUUID(e.target.value)}
          ></input>
        </div>
        <button className={s.LogBtn} onClick={() => DepartmentLogin()}>
          Dept. Login
        </button>
      </div>
    </div>
  );
}
